---
- name: Ensure docker is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

  tags: deploy

- name: Deploy web app
  block: 
  - name: Create directory for web app
    ansible.builtin.file:
      name: "{{ app_dir }}"
      state: directory

  - name: Copy docker-compose template
    ansible.builtin.template:
      src: templates/docker-compose.yml.j2
      dest: "{{ app_dir }}/docker-compose.yml"

  - name: Start web app
    community.docker.docker_compose_v2:
      project_src: "{{ app_dir }}"
      state: present

    tags: deploy

- name: Wipe the web app
  ansible.builtin.include_tasks: 0-wipe.yml
  when: web_app_full_wipe
  tags: wipe
