version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5" 
        tag: "loki"
    deploy:
      resources:
        limits:
          memory: 100M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ./promtail.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5" 
        tag: "promtail"
    deploy:
      resources:
        limits:
          memory: 100M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5" 
        tag: "grafana"
    deploy:
      resources:
        limits:
          memory: 100M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  app_python:
    image: damirafliatonov/moscow-time-app:latest
    ports:
      - "8000:8000"
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5" 
        tag: "app_python"
    deploy:
      resources:
        limits:
          memory: 100M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - ./python-visits:/app/visits
  
  app_javascript:
    image: damirafliatonov/moscow-time-app-js:latest
    ports:
      - "3001:3000"
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5" 
        tag: "app_javascript"
    deploy:
      resources:
        limits:
          memory: 100M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - ./javascript-visits:/app/visits

  prometheus:
    image: prom/prometheus:v2.51.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5" 
        tag: "prometheus"
    deploy:
      resources:
        limits:
          memory: 100M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
