---
- name: Install Docker
  hosts: all
  become: true
  roles:
    - docker

  vars:
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_user: damir
    ansible_python_interpreter: /usr/bin/python3
