name: javascript app CI

on:
  push:
    paths:
      - 'app_javascript/**'
      - '.github/workflows/app_javascript.yml'
  pull_request:
    paths:
      - 'app_javascript/**'
      - '.github/workflows/app_javascript.yml'

defaults:
  run:
    working-directory: app_javascript/

jobs:

  build_and_test:
    timeout-minutes: 1
    runs-on: ubuntu-22.04
    name: Build and test
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: app_javascript/package-lock.json
    - name: Install dependencies
      run: |
        npm install
    - name: ci
      run: |
        npm ci
    - name: Tests
      run: |
        npm test

  lint:
    timeout-minutes: 2
    runs-on: ubuntu-22.04
    name: lint with eslint

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: app_javascript/package-lock.json

    - name: Install dependencies
      run: |
        npm install

    - name: Lint
      run: |
        npm run lint


  docker-push:
    timeout-minutes: 3
    runs-on: ubuntu-22.04
    name: Push Docker image to Docker Hub

    steps:
    - name: Checkout
      uses: actions/checkout@v4    
    
    - name: Sign in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: build and push
      uses: docker/build-push-action@v5
      with:
        context: app_javascript
        file: ./app_javascript/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/moscow-time-app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  snyk:
    timeout-minutes: 3
    runs-on: ubuntu-22.04
    name: Snyk Vulnerability Checks

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Snyk
      uses: snyk/actions/node@master
      with:
          args: --skip-unresolved app_javascript/
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
