name: python app CI

on:
  push:
    paths:
      - 'app_python/**'
  pull_request:
    paths:
      - 'app_python/**'

defaults:
  run:
    working-directory: app_python

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and test

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Tests
      run: |
        python -m pytest tests/unit/test.py 

  lint:
    runs-on: ubuntu-latest
    name: lint with flake8

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Lint
      run: |
        pip install flake8
        flake8 main.py tests/unit/test.py

  docker-push:
    runs-on: ubuntu-latest
    name: Push Docker image to Docker Hub

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Sign in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - uses: docker/setup-buildx-action@v3
    - name: build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/moscow-time-app:latest
